# -*- coding: utf-8 -*-
"""model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrA-GhTi9WeocDaWG2jt_1Ef7RQsgOG2
"""

import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout


# -----------------------------------
# PREPARE DATA FOR LSTM
# -----------------------------------
def prepare_lstm_data(data, time_step=60):
    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(data)

    X, y = [], []
    for i in range(time_step, len(scaled)):
        X.append(scaled[i-time_step:i, 0])
        y.append(scaled[i, 0])

    X, y = np.array(X), np.array(y)
    X = X.reshape(X.shape[0], X.shape[1], 1)

    return X, y, scaler


# -----------------------------------
# TRAIN LSTM MODEL
# -----------------------------------
def train_lstm(X, y):
    split = int(0.8 * len(X))
    X_train, X_test = X[:split], X[split:]
    y_train, y_test = y[:split], y[split:]

    model = Sequential([
        LSTM(50, return_sequences=True, input_shape=(X.shape[1], 1)),
        Dropout(0.2),
        LSTM(50),
        Dropout(0.2),
        Dense(1)
    ])

    model.compile(optimizer="adam", loss="mse")
    model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

    preds = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, preds))

    return model, rmse


# -----------------------------------
# NEXT DAY PRICE PREDICTION
# -----------------------------------
def predict_next_price(model, data, scaler):
    last_60 = data[-60:].values
    last_60 = scaler.transform(last_60)
    last_60 = last_60.reshape(1, 60, 1)

    prediction = model.predict(last_60)
    prediction = scaler.inverse_transform(prediction)

    return prediction[0][0]


# -----------------------------------
# TRADE SIGNAL (EDUCATIONAL)
# -----------------------------------
def generate_trade_signal(current_price, predicted_price, threshold=0.5):
    if predicted_price > current_price + threshold:
        return "BUY 📈"
    elif predicted_price < current_price - threshold:
        return "SELL 📉"
    else:
        return "HOLD ⏸"

